// flow-typed signature: 20fbd256a32f18430a7d4ee225a88be4
// flow-typed version: <<STUB>>/blessed-contrib_v^4.8.5/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blessed-contrib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blessed-contrib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blessed-contrib/lib/layout/carousel' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/layout/grid' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/server-utils' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/utils' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/canvas' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/charts/bar' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/charts/line' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/charts/stacked-bar' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/donut' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/gauge-list' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/gauge' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/lcd' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/log' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/map' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/markdown' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/picture' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/sparkline' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/table' {
  declare module.exports: any;
}

declare module 'blessed-contrib/lib/widget/tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blessed-contrib/index' {
  declare module.exports: $Exports<'blessed-contrib'>;
}
declare module 'blessed-contrib/index.js' {
  declare module.exports: $Exports<'blessed-contrib'>;
}
declare module 'blessed-contrib/lib/layout/carousel.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/layout/carousel'>;
}
declare module 'blessed-contrib/lib/layout/grid.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/layout/grid'>;
}
declare module 'blessed-contrib/lib/server-utils.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/server-utils'>;
}
declare module 'blessed-contrib/lib/utils.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/utils'>;
}
declare module 'blessed-contrib/lib/widget/canvas.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/canvas'>;
}
declare module 'blessed-contrib/lib/widget/charts/bar.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/charts/bar'>;
}
declare module 'blessed-contrib/lib/widget/charts/line.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/charts/line'>;
}
declare module 'blessed-contrib/lib/widget/charts/stacked-bar.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/charts/stacked-bar'>;
}
declare module 'blessed-contrib/lib/widget/donut.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/donut'>;
}
declare module 'blessed-contrib/lib/widget/gauge-list.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/gauge-list'>;
}
declare module 'blessed-contrib/lib/widget/gauge.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/gauge'>;
}
declare module 'blessed-contrib/lib/widget/lcd.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/lcd'>;
}
declare module 'blessed-contrib/lib/widget/log.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/log'>;
}
declare module 'blessed-contrib/lib/widget/map.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/map'>;
}
declare module 'blessed-contrib/lib/widget/markdown.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/markdown'>;
}
declare module 'blessed-contrib/lib/widget/picture.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/picture'>;
}
declare module 'blessed-contrib/lib/widget/sparkline.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/sparkline'>;
}
declare module 'blessed-contrib/lib/widget/table.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/table'>;
}
declare module 'blessed-contrib/lib/widget/tree.js' {
  declare module.exports: $Exports<'blessed-contrib/lib/widget/tree'>;
}
