// flow-typed signature: 67ecfee3204d70962cf6dd9ecf939aeb
// flow-typed version: <<STUB>>/blessed_v^0.1.81/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blessed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blessed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blessed/bin/tput' {
  declare module.exports: any;
}

declare module 'blessed/browser/transform' {
  declare module.exports: any;
}

declare module 'blessed/example/ansi-viewer/index' {
  declare module.exports: any;
}

declare module 'blessed/example/ansi-viewer/singlebyte' {
  declare module.exports: any;
}

declare module 'blessed/example/blessed-telnet' {
  declare module.exports: any;
}

declare module 'blessed/example/index' {
  declare module.exports: any;
}

declare module 'blessed/example/multiplex' {
  declare module.exports: any;
}

declare module 'blessed/example/simple-form' {
  declare module.exports: any;
}

declare module 'blessed/example/time' {
  declare module.exports: any;
}

declare module 'blessed/example/widget' {
  declare module.exports: any;
}

declare module 'blessed/lib/alias' {
  declare module.exports: any;
}

declare module 'blessed/lib/blessed' {
  declare module.exports: any;
}

declare module 'blessed/lib/colors' {
  declare module.exports: any;
}

declare module 'blessed/lib/events' {
  declare module.exports: any;
}

declare module 'blessed/lib/gpmclient' {
  declare module.exports: any;
}

declare module 'blessed/lib/helpers' {
  declare module.exports: any;
}

declare module 'blessed/lib/keys' {
  declare module.exports: any;
}

declare module 'blessed/lib/program' {
  declare module.exports: any;
}

declare module 'blessed/lib/tput' {
  declare module.exports: any;
}

declare module 'blessed/lib/unicode' {
  declare module.exports: any;
}

declare module 'blessed/lib/widget' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/ansiimage' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/bigtext' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/box' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/button' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/checkbox' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/element' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/filemanager' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/form' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/image' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/input' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/layout' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/line' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/list' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/listbar' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/listtable' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/loading' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/log' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/message' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/node' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/overlayimage' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/progressbar' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/prompt' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/question' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/radiobutton' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/radioset' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/screen' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/scrollablebox' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/scrollabletext' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/table' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/terminal' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/text' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/textarea' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/textbox' {
  declare module.exports: any;
}

declare module 'blessed/lib/widgets/video' {
  declare module.exports: any;
}

declare module 'blessed/vendor/tng' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blessed/bin/tput.js' {
  declare module.exports: $Exports<'blessed/bin/tput'>;
}
declare module 'blessed/browser/transform.js' {
  declare module.exports: $Exports<'blessed/browser/transform'>;
}
declare module 'blessed/example/ansi-viewer/index.js' {
  declare module.exports: $Exports<'blessed/example/ansi-viewer/index'>;
}
declare module 'blessed/example/ansi-viewer/singlebyte.js' {
  declare module.exports: $Exports<'blessed/example/ansi-viewer/singlebyte'>;
}
declare module 'blessed/example/blessed-telnet.js' {
  declare module.exports: $Exports<'blessed/example/blessed-telnet'>;
}
declare module 'blessed/example/index.js' {
  declare module.exports: $Exports<'blessed/example/index'>;
}
declare module 'blessed/example/multiplex.js' {
  declare module.exports: $Exports<'blessed/example/multiplex'>;
}
declare module 'blessed/example/simple-form.js' {
  declare module.exports: $Exports<'blessed/example/simple-form'>;
}
declare module 'blessed/example/time.js' {
  declare module.exports: $Exports<'blessed/example/time'>;
}
declare module 'blessed/example/widget.js' {
  declare module.exports: $Exports<'blessed/example/widget'>;
}
declare module 'blessed/index' {
  declare module.exports: $Exports<'blessed'>;
}
declare module 'blessed/index.js' {
  declare module.exports: $Exports<'blessed'>;
}
declare module 'blessed/lib/alias.js' {
  declare module.exports: $Exports<'blessed/lib/alias'>;
}
declare module 'blessed/lib/blessed.js' {
  declare module.exports: $Exports<'blessed/lib/blessed'>;
}
declare module 'blessed/lib/colors.js' {
  declare module.exports: $Exports<'blessed/lib/colors'>;
}
declare module 'blessed/lib/events.js' {
  declare module.exports: $Exports<'blessed/lib/events'>;
}
declare module 'blessed/lib/gpmclient.js' {
  declare module.exports: $Exports<'blessed/lib/gpmclient'>;
}
declare module 'blessed/lib/helpers.js' {
  declare module.exports: $Exports<'blessed/lib/helpers'>;
}
declare module 'blessed/lib/keys.js' {
  declare module.exports: $Exports<'blessed/lib/keys'>;
}
declare module 'blessed/lib/program.js' {
  declare module.exports: $Exports<'blessed/lib/program'>;
}
declare module 'blessed/lib/tput.js' {
  declare module.exports: $Exports<'blessed/lib/tput'>;
}
declare module 'blessed/lib/unicode.js' {
  declare module.exports: $Exports<'blessed/lib/unicode'>;
}
declare module 'blessed/lib/widget.js' {
  declare module.exports: $Exports<'blessed/lib/widget'>;
}
declare module 'blessed/lib/widgets/ansiimage.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/ansiimage'>;
}
declare module 'blessed/lib/widgets/bigtext.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/bigtext'>;
}
declare module 'blessed/lib/widgets/box.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/box'>;
}
declare module 'blessed/lib/widgets/button.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/button'>;
}
declare module 'blessed/lib/widgets/checkbox.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/checkbox'>;
}
declare module 'blessed/lib/widgets/element.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/element'>;
}
declare module 'blessed/lib/widgets/filemanager.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/filemanager'>;
}
declare module 'blessed/lib/widgets/form.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/form'>;
}
declare module 'blessed/lib/widgets/image.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/image'>;
}
declare module 'blessed/lib/widgets/input.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/input'>;
}
declare module 'blessed/lib/widgets/layout.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/layout'>;
}
declare module 'blessed/lib/widgets/line.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/line'>;
}
declare module 'blessed/lib/widgets/list.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/list'>;
}
declare module 'blessed/lib/widgets/listbar.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/listbar'>;
}
declare module 'blessed/lib/widgets/listtable.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/listtable'>;
}
declare module 'blessed/lib/widgets/loading.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/loading'>;
}
declare module 'blessed/lib/widgets/log.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/log'>;
}
declare module 'blessed/lib/widgets/message.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/message'>;
}
declare module 'blessed/lib/widgets/node.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/node'>;
}
declare module 'blessed/lib/widgets/overlayimage.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/overlayimage'>;
}
declare module 'blessed/lib/widgets/progressbar.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/progressbar'>;
}
declare module 'blessed/lib/widgets/prompt.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/prompt'>;
}
declare module 'blessed/lib/widgets/question.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/question'>;
}
declare module 'blessed/lib/widgets/radiobutton.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/radiobutton'>;
}
declare module 'blessed/lib/widgets/radioset.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/radioset'>;
}
declare module 'blessed/lib/widgets/screen.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/screen'>;
}
declare module 'blessed/lib/widgets/scrollablebox.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/scrollablebox'>;
}
declare module 'blessed/lib/widgets/scrollabletext.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/scrollabletext'>;
}
declare module 'blessed/lib/widgets/table.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/table'>;
}
declare module 'blessed/lib/widgets/terminal.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/terminal'>;
}
declare module 'blessed/lib/widgets/text.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/text'>;
}
declare module 'blessed/lib/widgets/textarea.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/textarea'>;
}
declare module 'blessed/lib/widgets/textbox.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/textbox'>;
}
declare module 'blessed/lib/widgets/video.js' {
  declare module.exports: $Exports<'blessed/lib/widgets/video'>;
}
declare module 'blessed/vendor/tng.js' {
  declare module.exports: $Exports<'blessed/vendor/tng'>;
}
