// flow-typed signature: e3c90aca54a9ff73584c2e158b0458f3
// flow-typed version: <<STUB>>/ethers-wallet_v^2.1.8/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethers-wallet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethers-wallet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethers-wallet/hdnode' {
  declare module.exports: any;
}

declare module 'ethers-wallet/secret-storage' {
  declare module.exports: any;
}

declare module 'ethers-wallet/signing-key' {
  declare module.exports: any;
}

declare module 'ethers-wallet/wallet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethers-wallet/hdnode.js' {
  declare module.exports: $Exports<'ethers-wallet/hdnode'>;
}
declare module 'ethers-wallet/index' {
  declare module.exports: $Exports<'ethers-wallet'>;
}
declare module 'ethers-wallet/index.js' {
  declare module.exports: $Exports<'ethers-wallet'>;
}
declare module 'ethers-wallet/secret-storage.js' {
  declare module.exports: $Exports<'ethers-wallet/secret-storage'>;
}
declare module 'ethers-wallet/signing-key.js' {
  declare module.exports: $Exports<'ethers-wallet/signing-key'>;
}
declare module 'ethers-wallet/wallet.js' {
  declare module.exports: $Exports<'ethers-wallet/wallet'>;
}
