// flow-typed signature: 6a2d000186f6aab8f93e340db09c5083
// flow-typed version: <<STUB>>/@colony/eslint-config-colony_v^7.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@colony/eslint-config-colony'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@colony/eslint-config-colony' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@colony/eslint-config-colony/index' {
  declare module.exports: $Exports<'@colony/eslint-config-colony'>;
}
declare module '@colony/eslint-config-colony/index.js' {
  declare module.exports: $Exports<'@colony/eslint-config-colony'>;
}
